import type { Meta, StoryObj } from "@storybook/react";
import { ProductCard } from "@pincommerce/agency-web-ui";
const meta = { title: "Commerce/ProductCard", component: ProductCard, args: { title: "Reference Product", priceLabel: "₹1,999" } } satisfies Meta<typeof ProductCard>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
export const Discounted: Story = { args: { state: "discounted", priceLabel: "₹1,499", previousPriceLabel: "₹1,999" } };
export const OutOfStock: Story = { args: { state: "out-of-stock" } };
export const Loading: Story = { args: { state: "loading" } };
export const Failure: Story = { args: { state: "failure" } };
